### ISSUE TITLE
blanket component stacking problem and conflict with children's pointer events

### ISSUE THREAD

**Issue by novadeveloper14** [selsa-inube/design-system#104]
When using a component inside the blanket is not allowing to interact with the children possibly can be the style "Pointer-Events: None;" and also the blanket is not exceeding the screen wherever it is used so it generates stacking problems.

**Comment by wfercanas** [comment]
@novadeveloper14 , la replicación de este issue se puede hacer en la rama 181 de linpar?

**Comment by novadeveloper14** [comment]
@wfercanas si señor

**Comment by wfercanas** [comment]
La propiedad pointer-events se hereda en CSS. Por lo que todos los hijos del Blanket van a heredar el `pointer-events: none` que tiene definido.
Esta propiedad mata todas las interacciones con el mouse (mouse-events), haciendo que componentes como el DecisionModal queden inservibles. Hay que eliminar esa propiedad para normalizar el uso de los children del Blanket.

IDS-85
