### ISSUE TITLE
fix styles of the props iconBefore and iconAfter of TextField component

### ISSUE THREAD

**Issue by ANGIECATHERINEP** [selsa-inube/design-system#112]
there are some bugs with the styles of the icons that are added to the input. because when entering the iconBefore prop, a part of the border of the input disappears and when entering the iconAfter, the icon is very attached to the right edge of the input

**Comment by wfercanas** [comment]
@ANGIECATHERINEP , este no es un problema del `<TextField />`, él funciona correctamente.
El problema es que el container con el que están aplicando estilos en la página está haciendo uso de selectores CSS complejos que están afectando inclusive al `<TextField />` de forma directa. Para el caso del error, en styles.js se está definiendo:

```js
  div > div:last-of-type > div:nth-of-type(2) > div {
    max-width: 280px;
  }
```

**Conclusión**: Si apagas ese max-width, ya el componente funciona correctamente. El equipo Linpar tendría que resolver el problema a nivel de como está armando el layout.
