### ISSUE TITLE
change the typography token of the button component

### ISSUE THREAD

**Issue by ANGIECATHERINEP** [selsa-inube/design-system#115]
in the button component, the font-size of the text is 16px and according to the figma mockups it should be 14px. For this reason, it would have to change the typography token in the "wide" option of the spacing prop.

**Comment by wfercanas** [comment]
Se evaluará el uso de `<Text />` dentro del `<Button />` para evitar el uso directo de typography tokens y que de esa manera sea más consistente su uso.
