### ISSUE TITLE
change the value of the property  font-size in TextField component

### ISSUE THREAD

**Issue by ANGIECATHERINEP** [selsa-inube/design-system#127]
En el componente TextField el valor del  font-size del input de las dos opciones de la prop size  (compact y wide) es de 14px , pero según los mockups deberían ser de 16px en las dos opciones.

**Comment by Andresbl123** [comment]
Se realiza el ajuste, pasa a per review

**Comment by ANGIECATHERINEP** [comment]
se revisa el requerimiento y funciona correctamente
