### ISSUE TITLE
Añadir padding a la derecha del componente <Tabs />

### ISSUE THREAD

**Issue by Sebas3245** [selsa-inube/design-system#145]
# Añadir padding a la derecha del componente <Tabs />
Sucede que actualmente al componente <Tabs /> al pasarle el listado de tabs el primer tab tiene un padding a la izquierda y esto esta bien, sin embargo, el ultimo tab queda pegado a la derecha del contenedor de tabs cuando la pantalla es tablet o mobile:

![image](https://github.com/selsa-inube/design-system/assets/55991750/cc24e28a-b3d5-453d-ab81-935a8dc30612)
![image](https://github.com/selsa-inube/design-system/assets/55991750/c7e45f7d-e626-4b72-b6b0-987b97628355)

Seria ideal que el ultimo tab también tenga el padding a la derecha.

**Comment by Andresbl123** [comment]
pasa a review

**Comment by Andresbl123** [comment]
Pasa a Done
