### ISSUE TITLE
El componente <Table> no representa correctamente el contenido debido al content de actions.

### ISSUE THREAD

**Issue by CristianRojas-47** [selsa-inube/design-system#182]
El componente <Table> de momento para el content de las actions recibe un "PropTypes.node", pero este realmente recibe una función,  a continuación agrego una imagen de ejemplo de cómo se define las funciones en content: 

![Captura de pantalla 2023-06-15 174015](https://github.com/selsa-inube/design-system/assets/93727887/7337ce87-0a68-43b1-8dd1-0a9def4d2692)
![image](https://github.com/selsa-inube/design-system/assets/93727887/3e1f4c48-2652-431c-b913-99cc1442030b)

**Comment by wfercanas** [comment]
Actions no es ni un node ni una function sino un array de objetos. Dentro de cada uno de esos objetos sí hay definidas las propiedades action y content, por lo que lo primero es asegurar que con propTypes estemos recibiendo ese array de objetos con esas propiedades.
Ahora, la primera de ellas  ("action") es un string, mientras que la segunda es una función. Esta función retorna al final un componente de React y es necesaria la función porque la tabla la va a ejecutar y le va a pasar como parámetro el entry o la fila que en ese momento esté procesando. De esa manera podemos relacionar ese componente retornado con los valores de la fila que se está pintando.

Conclusión: lo primero es asegurar el array de objetos, que se un array de acciones. Luego, es asegurar la estructura interna de esos objetos, que tienen una propiedad que es un string y otra que es una función.

@cmarin001

**Comment by CristianRojas-47** [comment]
La issue fue solucionada correctamente.
