### ISSUE TITLE
In the `textAlign` props of the `<Text />` component, no proper typing is being done,

### ISSUE THREAD

**Issue by Andresbl123** [selsa-inube/design-system#615]
In the `textAlign` props of the `<Text />` component, no proper typing is being done, this should be of specific strings that are defined in the props file, but it is not used properly. 
![image](https://github.com/selsa-inube/design-system/assets/74839801/a1659ec5-8ad9-4ee7-b4e7-b9325a119b09)
![image](https://github.com/selsa-inube/design-system/assets/74839801/ead34548-bdb4-46d8-89c3-cb504e8a9254)

 we did not assign the literal type `as const` to the constant, I propose: to create a direct `type` ` AlignOptions = "start" | "center" | "end" | "justify";` to which we avoid the declaration of the constant with the literal types.

**Comment by cmarin001** [comment]
This issue was solve on the newest version of design-system library 5.9.0
