### ISSUE TITLE
Fix: Correct <Tabs/> Fix tab behavior

### ISSUE THREAD

**Issue by LoweLeo** [selsa-inube/design-system#641]
Check the behavior that is occurring in the "tabs" component when clicking in the gap or outside the tabs changes strangely

![imagen](https://github.com/selsa-inube/design-system/assets/152199887/2c08486d-7d56-4fb1-81bb-31ead9b24b5f)
![imagen](https://github.com/selsa-inube/design-system/assets/152199887/9c55601e-6bdb-4514-bf86-94de41bdb80e)

Correct according to Figma documentation. Remember that the blue line allows the user to locate themselves within the navigation and should not affect the padding of the component.

**Comment by cmarin001** [comment]
This issue was solved and is on main branch already
