### ISSUE TITLE
Update the component TextField

### ISSUE THREAD

**Issue by LoweLeo** [selsa-inube/design-system#645]
The user must be able to identify when a "readOnly" field is required or not

![imagen](https://github.com/selsa-inube/design-system/assets/152199887/b4849801-78ef-42f6-bd6d-2712e5e3f969)

The TextField component receives an update to its "Required" instance, which should be able to set the readOnly state with the required tag.

**Comment by Andresbl123** [comment]
update performed according to the designs

**Comment by Andresbl123** [comment]
resolved in v5.14.0
