### ISSUE TITLE
the `<Select />` component can be readOnly when requested

### ISSUE THREAD

**Issue by LoweLeo** [selsa-inube/design-system#646]
The user must be able to identify when a "readOnly" field is required or not

![imagen](https://github.com/selsa-inube/design-system/assets/152199887/6d58b55a-d9c7-4366-a889-f728e455e93a)

The Select component receives an update to its "Required" instance, which should be able to set the readOnly state with the required tag.

**Comment by Andresbl123** [comment]
setting made, the `<Select />` component can be readOnly when it is required.

**Comment by Andresbl123** [comment]
resolved in v5.14.0
