### ISSUE TITLE
Mobile Responsiveness Issue with `<Assisted/>` Component Display

### ISSUE THREAD

**Issue by cmarin001** [selsa-inube/design-system#647]
We are presently confronting a technical challenge where the `<Assisted/>` component is not rendering as expected on mobile devices. The issue manifests as a lack of proper responsiveness, which could potentially be due to CSS media queries not effectively adapting the layout or possible JavaScript execution errors affecting dynamic behavior. This problem requires immediate attention to ensure a seamless user interface across all device viewports.

![image](https://github.com/selsa-inube/design-system/assets/45011420/51ca2070-3bdb-41ab-9207-6aeaf502f7c4)

**Comment by Andresbl123** [comment]
The adjustment was made, and it now fits the size of the container.
