### ISSUE TITLE
Revision of Navigation Component Design and Layout Adjustment in Accordance with Figma Specifications

### ISSUE THREAD

**Issue by cmarin001** [selsa-inube/design-system#653]
initiate a meticulous revision of the navigation component design as outlined in the Figma documentation. Specifically, scrutinize line 101 within the OneSection function, where the expression {navigation.sections[section].name} is implemented. This particular code segment may be the root of the existing operational discrepancies. Additionally, a comprehensive adjustment to the layout structure is necessitated to align with the updated design parameters. This adjustment should encompass a thorough review of the CSS properties associated with the layout, ensuring that they are in sync with the intended visual and functional specifications as per the Figma design. It's imperative to validate the responsiveness and cross-browser compatibility of these changes to maintain a consistent user experience across various devices and browsers

Here is how it appears now:
![image](https://github.com/selsa-inube/design-system/assets/45011420/b5499ca1-c761-43be-b75d-39d8c9d8dda8)

Here is how it should be:
![image](https://github.com/selsa-inube/design-system/assets/45011420/f0b021e7-cbba-4dc6-a160-30924ae0114b)

**Comment by Andresbl123** [comment]
Adjustment made, awaiting release

**Comment by Andresbl123** [comment]
resolved in v5.14.0
